apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-service-sit
  namespace: openshift-gitops
  labels:
    app: payment-service
    environment: sit
spec:
  project: default
  sources:
    - repoURL: https://github.com/gehlotvishnu/gitops-demos.git
      targetRevision: main
      path: charts/payment-service
      helm:
        releaseName: payment-service
        valueFiles:
          - $gitops-config/deploy-config/sit/payment-service/values.yaml
          - $app-config/app-config/sit/payment-service/application.properties
    - repoURL: https://github.com/gehlotvishnu/gitops-demos.git
      targetRevision: main
      ref: gitops-config
    - repoURL: https://github.com/gehlotvishnu/spring-boot-config.git
      targetRevision: main
      ref: app-config
  destination:
    server: https://kubernetes.default.svc
    namespace: payment-service-sit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
