apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-demo-dev
  namespace: openshift-gitops
  labels:
    environment: dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/gehlotvishnu/gitops-demos.git
    targetRevision: main
    path: charts/spring-boot-app
    helm:
      valueFiles:
        - ../../envs/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-boot-dev
  syncPolicy:
    automated:
      prune: true        # Delete resources removed from git
      selfHeal: true     # Revert manual changes in cluster
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
