apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service-dev
  namespace: openshift-gitops
  labels:
    app: order-service
    environment: dev
spec:
  project: default
  sources:
    - repoURL: https://github.com/gehlotvishnu/gitops-demos.git
      targetRevision: main
      path: charts/order-service
      helm:
        releaseName: order-service
        valueFiles:
          - $gitops-config/deploy-config/dev/order-service/values.yaml
          - $app-config/app-config/dev/order-service/values.yaml
    - repoURL: https://github.com/gehlotvishnu/gitops-demos.git
      targetRevision: main
      ref: gitops-config
    - repoURL: https://github.com/gehlotvishnu/spring-boot-config.git
      targetRevision: main
      ref: app-config
  destination:
    server: https://kubernetes.default.svc
    namespace: order-service-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
